name: nixtlats
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - pandas
  - plotly
  - pip:
    - black
    - nbdev
    - mypy
    - flake8
    - python-dotenv
    - statsforecast
    - requests
    - openbb
